In [2]:
import pandas as pd
import numpy as np

In [21]:
observations = pd.read_csv('observations.csv')
media = pd.read_csv('media.csv')
events = pd.read_csv('events.csv')
deployments = pd.read_csv('deployments.csv')

alldata_list = (observations, 
                media, 
                events, 
                deployments)

In [26]:
# for data in alldata_list:
#     print(len(data))

observations
# observations.head()

,observationID,deploymentID,mediaID,eventID,eventStart,eventEnd,observationLevel,observationType,scientificName,count,...,behavior,individualID,bboxX,bboxY,bboxWidth,bboxHeight,classificationMethod,classifiedBy,classificationProbability,observationComments
0,obs_20220801001635_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(...,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z,event,blank,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,human,Jitske Schreijer,NaN,NaN
1,obs_20220801001635_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(...,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z,event,blank,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,human,Jitske Schreijer,NaN,NaN
2,obs_20220801003924_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-39-24_(...,2022-07-31T22:39:24+00Z,2022-07-31T22:39:32+00Z,event,blank,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,machine,Western Europe species model Version 2 (deprec...,NaN,NaN
3,obs_20220801120024_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,artis_18_wildlifecamera1_2022-08-01_12-00-24_(12),NaN,NaN,NaN,media,blank,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,human,Jitske Schreijer,NaN,NaN
4,obs_20220802120027_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,artis_18_wildlifecamera1_2022-08-02_12-00-27_(13),NaN,NaN,NaN,media,blank,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,machine,Western Europe species model Version 2 (deprec...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36538,obs_20231028183334_artis_24_wildlifecamera1_20...,artis_24_wildlifecamera1,artis_24_wildlifecamera1_2023-10-28_18-33-34_(2),NaN,NaN,NaN,media,animal,Scolopax rusticola,1,...,NaN,NaN,850.832356,652.50,582.977726,603.00,human,Rotem Zilber,NaN,NaN
36539,obs_20231028183332_artis_24_wildlifecamera1_20...,artis_24_wildlifecamera1,artis_24_wildlifecamera1_2023-10-28_18-33-32_(3),NaN,NaN,NaN,media,animal,Scolopax rusticola,1,...,NaN,NaN,884.595545,537.75,763.048066,713.25,human,Rotem Zilber,NaN,NaN
36540,obs_20231028183329_artis_24_wildlifecamera1_20...,artis_24_wildlifecamera1,artis_24_wildlifecamera1_2023-10-28_18-33-29_(4),NaN,NaN,NaN,media,animal,Scolopax rusticola,1,...,NaN,NaN,384.900352,672.75,882.344666,576.00,human,Rotem Zilber,NaN,NaN
36541,obs_20231028183327_artis_24_wildlifecamera1_20...,artis_24_wildlifecamera1,artis_24_wildlifecamera1_2023-10-28_18-33-27_(5),NaN,NaN,NaN,media,animal,Scolopax rusticola,1,...,NaN,NaN,814.818288,780.75,405.158265,441.00,human,Rotem Zilber,NaN,NaN
36542,obs_20231028183324_artis_24_wildlifecamera1_20...,artis_24_wildlifecamera1,artis_24_wildlifecamera1_2023-10-28_18-33-24_(6),NaN,NaN,NaN,media,animal,Scolopax rusticola,1,...,NaN,NaN,794.560375,855.00,407.409144,369.00,human,Rotem Zilber,NaN,NaN

In [32]:
mergedTest = observations.merge(events, on='eventID')
mergedTest

,observationID,deploymentID,mediaID_x,eventID,eventStart_x,eventEnd_x,observationLevel,observationType,scientificName,count,...,bboxWidth,bboxHeight,classificationMethod,classifiedBy,classificationProbability,observationComments,mediaID_y,mediaCount,eventStart_y,eventEnd_y
0,obs_20220801001635_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(...,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z,event,blank,NaN,0,...,NaN,NaN,human,Jitske Schreijer,NaN,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-37_(54),5.0,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z
1,obs_20220801001635_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(...,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z,event,blank,NaN,0,...,NaN,NaN,human,Jitske Schreijer,NaN,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-41_(52),5.0,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z
2,obs_20220801001635_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(...,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z,event,blank,NaN,0,...,NaN,NaN,human,Jitske Schreijer,NaN,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-43_(51),5.0,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z
3,obs_20220801001635_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(...,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z,event,blank,NaN,0,...,NaN,NaN,human,Jitske Schreijer,NaN,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-39_(53),5.0,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z
4,obs_20220801001635_artis_18_wildlifecamera1_20...,artis_18_wildlifecamera1,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(...,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z,event,blank,NaN,0,...,NaN,NaN,human,Jitske Schreijer,NaN,NaN,artis_18_wildlifecamera1_2022-08-01_00-16-35_(55),5.0,2022-07-31T22:16:35+00Z,2022-07-31T22:16:43+00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202629,obs_20211029220821_artis_25_wildlifecamera1_20...,artis_25_wildlifecamera1,NaN,artis_25_wildlifecamera1_2021-10-29_22-08-21_(...,2021-10-29T20:08:21+00Z,2021-10-29T20:08:25+00Z,event,animal,Rattus norvegicus,1,...,NaN,NaN,human,Rotem Zilber,NaN,NaN,artis_25_wildlifecamera1_2021-10-29_22-08-23_(...,5.0,2021-10-29T20:08:21+00Z,2021-10-29T20:08:25+00Z
202630,obs_20211029220821_artis_25_wildlifecamera1_20...,artis_25_wildlifecamera1,NaN,artis_25_wildlifecamera1_2021-10-29_22-08-21_(...,2021-10-29T20:08:21+00Z,2021-10-29T20:08:25+00Z,event,animal,Rattus norvegicus,1,...,NaN,NaN,human,Rotem Zilber,NaN,NaN,artis_25_wildlifecamera1_2021-10-29_22-08-24_(...,5.0,2021-10-29T20:08:21+00Z,2021-10-29T20:08:25+00Z
202631,obs_20211029220821_artis_25_wildlifecamera1_20...,artis_25_wildlifecamera1,NaN,artis_25_wildlifecamera1_2021-10-29_22-08-21_(...,2021-10-29T20:08:21+00Z,2021-10-29T20:08:25+00Z,event,animal,Rattus norvegicus,1,...,NaN,NaN,human,Rotem Zilber,NaN,NaN,artis_25_wildlifecamera1_2021-10-29_22-08-25_(...,5.0,2021-10-29T20:08:21+00Z,2021-10-29T20:08:25+00Z
202632,obs_20211031120016_artis_25_wildlifecamera1_20...,artis_25_wildlifecamera1,NaN,artis_25_wildlifecamera1_2021-10-31_12-00-16_(...,2021-10-31T11:00:16+00Z,2021-10-31T11:00:20+00Z,event,blank,NaN,0,...,NaN,NaN,machine,Western Europe species model Version 1 (deprec...,NaN,NaN,artis_25_wildlifecamera1_2021-10-31_12-00-16_(...,2.0,2021-10-31T11:00:16+00Z,2021-10-31T11:00:20+00Z
202633,obs_20211031120016_artis_25_wildlifecamera1_20...,artis_25_wildlifecamera1,NaN,artis_25_wildlifecamera1_2021-10-31_12-00-16_(...,2021-10-31T11:00:16+00Z,2021-10-31T11:00:20+00Z,event,blank,NaN,0,...,NaN,NaN,machine,Western Europe species model Version 1 (deprec...,NaN,NaN,artis_25_wildlifecamera1_2021-10-31_12-00-20_(...,2.0,2021-10-31T11:00:16+00Z,2021-10-31T11:00:20+00Z